version: '3'
services:
  app:
    build:
      context: ruby-app
    tty: true
    env_file: ruby-app/.env
    stdin_open: true
    command: make app-start
    container_name: app
    depends_on:
      - sqs
      - db

  sqs:
    image: roribio16/alpine-sqs:latest
    container_name: sqs
    ports:
      - "9324:9324"
      - "9325:9325"

  db:
    image: postgres:9.6-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
